### ISSUE TITLE
Algolia search

### ISSUE THREAD

**Issue by adelerhof** [thingsym/hugo-theme-techdoc#27]
For me it produces a incomplete json in technote/public/algolia.json:

```text
[{"objectID":"f1229466f5a80e7cccdac452442f4756"},"objectID":"8c5128a009a51f04d0a8cf9aa96a1183"},{"objectID":"a9fee9dbb4fee679405e2bf8a6408cd9"}]
```

Which results in an incomplete index at Algolia:

```text
{
  "objectID": "ffe689385f2400c55dc72d63cbb5f62c"
}
```

According to the solution mentioned in issue 22 it should look like:

```text
[
    {
        "content": "First 1000 words here...",
        "date": "2019-12-28 00:00:00",
        "href": "https://yourdomain.com/2019/12/28/lengthy-blog-post",
        "objectID": "163846258b8839cf2591a6b88c522d84_0",
        "order": 0,
        "tags": ["conferences"],
        "title": "A lengthy blog post"
    }
]
````

Could you please explain how to implement this, or point me in the direct of my mistake?

Quote issue 22:

I have found solution. Need load json file to algolia manually (more info you can find there https://www.bennet.org/blog/site-search-jamstack-hugo-algolia/ )

_Originally posted by @vglu in https://github.com/thingsym/hugo-theme-techdoc/issues/22#issuecomment-621765893_

**Comment by vglu** [comment]
Hi,

on yours config.toml 
how you setup algolia section? 
my example looks like

# Algolia Search configure section
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
        "keywords",
    ...
        "summary"
     ]

**Comment by thingsym** [comment]
Hi @adelerhof,

Thank you for your issue.

What is the theme version?

If less than version 0.9.0, it may be caused by case sensitivity.
It was fixed in version 0.9.0.
Try modifying the config.toml file.

```
[Params]
```

Fixed below

```
[params]
```

**Comment by adelerhof** [comment]
@vglu , 

My config.toml looks like:

```toml
baseURL = "https://technotes.adelerhof.eu"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Technotes"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[Params]

    # Souce Code repository section
    description = "Technotes for future me"
    github_repository = "https://github.com/adelerhof/technote"
    version = ""

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/adelerhof/technote"

    # Analytic section
    google_analytics_id = "<id>" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "<key>" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    title = "Technotes"
    images = ["og-image.png"]
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards

    # Theme settings section
    # Theme color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu"

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts"
    ]

    # Algolia site search section
    # See https://www.algolia.com/doc/
    algolia_search_enable<name>"
    algolia_appId = "<id>"
    algolia_apiKey = "<key>" # Search-Only API Key

# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[params.algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]

```

Maybe important, my article headers look like:

```text
---
date: 2019-12-11
lastmod: 2019-12-18
publishdate: 2019-12-11

title: Technotes
description: Technotes for future me
images:
- blaataap.jpg
---

## Technotes for future me

Some epic story about stuff, I dunno either
```

and:

```text
---
title: "Auditd"
date: 2019-12-25
draft: false
---
```

@thingsym ,I build the site via Jenkins with a multistage docker build. I used git submodule to add the theme, I suppose i always uses the latest from the master branch?

```text
git submodule add https://github.com//thingsym/hugo-theme-techdoc
```

```text
# The Hugo version
ARG VERSION=0.72.0
```

@vglu , @thingsym , thanks for your reaction btw!

**Comment by adelerhof** [comment]
> Hi @adelerhof,
> 
> Thank you for your issue.
> 
> What is the theme version?
> 
> If less than version 0.9.0, it may be caused by case sensitivity.
> It was fixed in version 0.9.0.
> Try modifying the config.toml file.
> 
> ```
> [Params]
> ```
> 
> Fixed below
> 
> ```
> [params]
> ```

@thingsym , to be sure I changed it to lowercase, unfortunately it didn't solve the issue.

**Comment by adelerhof** [comment]
@vglu @thingsym , I did a diff of the config.toml, the part I missed was the output section:

```text
[outputs]
    home = ["HTML", "RSS", "Algolia"]
```

@thingsym , last weekend I copied also the layouts directory to the root, apparently you need that as well, Is there documentation which assets you absolutely need? The site worked without it, and I'm more or less using try and error what I need.
If I'm asking to much, please let me know.

Thanks
